---
all:
  children:
    molecule:
      hosts:
        ubuntu2604:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/ubuntu:26.04
          container_command: sleep 1d
        ubuntu2404:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/ubuntu:24.04
          container_command: sleep 1d
        debian13:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/debian:13
          container_command: sleep 1d
        debian12:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/debian:12
          container_command: sleep 1d
        fedora44:
          ansible_connection: containers.podman.podman
          container_image: registry.fedoraproject.org/fedora:44
          container_command: sleep 1d
        fedora43:
          ansible_connection: containers.podman.podman
          container_image: registry.fedoraproject.org/fedora:43
          container_command: sleep 1d
