---

- name: "Ensure specified user account ({{ item.name }}) exist with correct attributes"
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit, true) }}"
    uid: "{{ item.uid | default(omit, true) }}"
    group: "{{ item.group | default(omit, true) }}"
    groups: "{{ item.groups | default([], true) | join(',') | default(omit, true) }}"
    shell: "{{ item.shell | default(omit, true) }}"
    create_home: "{{ item.create_home | default(omit, true) }}"
    skeleton: "{{ item.skeleton | default(omit, true) }}"
    expires: "{{ item.expires | default(omit, true) }}"
    home: "{{ item.home | default(omit, true) }}"
    password: "{{ item.password | default(omit) }}"
    password_expire_max: "{{ item.password_expire_max | default(omit, true) }}"
    password_expire_min: "{{ item.password_expire_min | default(omit, true) }}"
    password_lock: "{{ item.password_lock | default(omit, true) }}"
    append: "{{ item.append | default(omit, true) }}"
    force: "{{ item.force | default(omit, true) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit, true) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit, true) }}"
    ssh_key_comment: "{{ item.ssh_key_comment | default(omit, true) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(omit, true) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(omit, true) }}"
    ssh_key_type: "{{ item.ssh_key_type | default(omit, true) }}"
    local: "{{ item.local | default(omit, true) }}"
    login_class: "{{ item.login_class | default(omit, true) }}"
    move_home: "{{ item.move_home | default(omit, true) }}"
    non_unique: "{{ item.non_unique | default(omit, true) }}"
    remove: "{{ item.remove | default(omit, true) }}"
    seuser: "{{ item.seuser | default(omit, true) }}"
    system: "{{ item.system | default(omit, true) }}"
    umask: "{{ item.umask | default(omit, true) }}"
    update_password: "{{ item.update_password | default(omit, true) }}"
    state: present
  register: user_info

- name: Set variables that uses user uid
  set_fact:
    xdg_runtime_dir: "/run/user/{{ user_info.uid }}"

- name: Check if user is lingering
  stat:
    path: "/var/lib/systemd/linger/{{ user_info.name }}"
  register: user_lingering
  when:
    - user_info.uid | int != 0
    - item.linger is defined


- name: Enable Lingering
  when:
    - item.linger is defined
    - item.linger == true
    - not user_lingering.stat.exists
  block:
    - name: Enabling lingering
      command: "loginctl enable-linger {{ user_info.name }}"
      changed_when: true
      when:
        - user_info.uid | int != 0

    - name: Add XDG_RUNTIME_DIR variable to .bashrc
      ansible.builtin.lineinfile:
        path: "{{ user_info.home }}/.bashrc"
        line: "export XDG_RUNTIME_DIR={{ xdg_runtime_dir }}"
        create: no
      when: user_info.uid | int != 0

- name: Disable Lingering
  when:
    - item.linger is defined
    - item.linger == false
    - user_lingering.stat.exists
  block:
    - name: Enabling lingering
      command: "loginctl disable-linger {{ user_info.name }}"
      changed_when: true
      when:
        - user_info.uid | int != 0

    - name: Remove XDG_RUNTIME_DIR variable from .bashrc
      ansible.builtin.lineinfile:
        path: "{{ user_info.home }}/.bashrc"
        line: "export XDG_RUNTIME_DIR={{ xdg_runtime_dir }}"
        create: no
        state: absent
      when: user_info.uid | int != 0
