---
- name: Ensure specified groups exist with correct attributes
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: present
  loop: "{{ user_group_add }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - user
    - config

- name: Ensure specified groups do not exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  loop: "{{ user_group_remove }}"
  tags:
    - user
    - config

- name: Ensure specified user accounts exist with correct attributes
  ansible.builtin.include_tasks: create_user.yml
  loop: "{{ user_account_add }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - user
    - config

- name: Refresh become password variable when requested by caller
  ansible.builtin.set_fact:
    ansible_become_pass: "{{ user_new_password }}"
  when: user_new_password | length > 0
  tags:
    - user
    - config

- name: Ensure specified user accounts do not exist
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ user_account_remove }}"
  tags:
    - user
    - config

- name: Add or remove aliases from user bashrc files
  vars:
    user_alias_home: "{{ '/root/.bashrc' if item.user == 'root' else '/home/' ~ item.user ~ '/.bashrc' }}"
  ansible.builtin.lineinfile:
    path: "{{ user_alias_home }}"
    regexp: '^alias\s+{{ item.alias | regex_escape }}='
    line: "alias {{ item.alias }}='{{ item.command }}'"
    state: "{{ item.state }}"
    mode: "0640"
    create: false
  loop: "{{ user_alias }}"
  loop_control:
    label: "{{ item.user }}:{{ item.alias }}"
  tags:
    - user
    - config
