---
- name: Prepare
  hosts: all
  tasks:

    - name: Update Ubuntu/Debian systems
      ansible.builtin.apt:
#        upgrade: dist
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install commom tools
      ansible.builtin.package:
        name: ['passwd', 'findutils', 'gawk']
        state: present
